app:
  version: '@project.version@'
spring:
  application:
    name: defence-in-depth
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/defence-in-depth
  config:
    import:
      'optional:aws-secretsmanager:defence-in-depth'
aws:
  secretsmanager:
    region: eu-west-1